install.packages("remotes")
remotes::install_github("alexpghayes/distributions3", 						# have to install this first or else countreg won't install successfully 
						ref="92fa9de94770544b9a59554936cbddb4cf5630fd")		# main branch's latest commit as of 26JUL24
remotes::install_version('topmodels', version="0.3-0", repos='http://R-Forge.R-project.org')	# most recent version as of 26JUL24
install.packages('dplyr')
install.packages('DT')
install.packages('ggplot2')
install.packages('ggtext')
install.packages('glmx')
install.packages('haven')
install.packages('magrittr')
install.packages('MASS')
install.packages('maxLik')
install.packages('mlogit')
install.packages('msm')
install.packages('nnet')
install.packages('pscl')
install.packages("rlang")
install.packages('shiny')
install.packages('shinyBS')
install.packages('shinycssloaders')
install.packages('shinyjqui')
install.packages('shinyjs')
install.packages('shinythemes')
install.packages('shinyWidgets')
install.packages('showtext')
install.packages('stargazer')
