install.packages('countreg', repos='http://R-Forge.R-project.org')
install.packages('dplyr')
install.packages('DT')
install.packages('ggplot2')
install.packages('ggtext')
install.packages('glmx')
install.packages('haven')
install.packages('magrittr')
install.packages('MASS')
install.packages('maxLik')
install.packages('mlogit')
install.packages('msm')
install.packages('nnet')
install.packages('pscl')
install.packages("remotes")
remotes::install_version("rlang", "0.4.10", repos="http://cran.us.r-project.org") # because not having this somehow throws an error for dplyr, though it shouldn't given the MRAN repo date.
install.packages('shiny')
install.packages('shinyBS')
install.packages('shinycssloaders')
install.packages('shinyjqui')
install.packages('shinyjs')
install.packages('shinythemes')
install.packages('shinyWidgets')
install.packages('showtext')
install.packages('stargazer')
