install.packages("countreg", repos="http://R-Forge.R-project.org")
install.packages('dplyr')
install.packages('DT')
install.packages('MASS')
install.packages('mlogit')
install.packages('msm')
install.packages('nnet')
install.packages('pscl')
install.packages('shiny')
install.packages('shinyBS')
install.packages('shinyjs')
install.packages('shinythemes')
