library(ggplot2)
library(magrittr)
library(stargazer)
library(shinyjs)
library(shinyBS)
library(shinyWidgets)
library(shinycssloaders)
library(shinyjqui)
library(MASS)
library(dplyr)
library(mlogit)
library(showtext)

# Install Roboto for ggplot2
font_add_google("Roboto", "Roboto")